on:
  push:
    branches: [master]
    
  workflow_dispatch:


jobs:
  # Build job
  one:
    runs-on: ubuntu-latest
    steps:
    - name: "Echo in file"
      run: echo "HELLOWORLD" > "secrets.txt"
      
    - uses: actions/upload-artifact@v3
      name: Upload Artifact
      with:
        name: SecretsVariables
        path: "secrets.txt"
  setup:
    name: Setup Azure VM
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
    - name: Run a one-line script
      run: echo "ONE" > new_file.txt
    - name: git config1
      run: git config user.name github-actions
    - name: git config2
      run: git config user.email github-actions@github.com
    - name: git status
      run: git status
    - name: stage changed files
      run: git add .
    - name: commit changed files
      run: git commit -m "Auto updating TODO.txt"
    - name: fetch from master
      run: git fetch origin master
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        force_with_lease: true
    - name: echo inputs
      run: echo "INPUTS"
