on:
  push:
  workflow_dispatch:
    inputs:
      vmSku:
        description: 'Virtual Machine SKU'     
        required: true
        default: 'Standard_B2ms'
      vmCount:
        description: 'Virtual Machine Count'     
        required: true-
        default: 2

jobs:
  setup:
    name: Setup Azure VM
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo "ONE"
    - name: switching from HTTPS to SSH
      run: git remote set-url origin ${{ secrets.ssh }}
    - name: check for changes
      run: git status
    - name: stage changed files
      run: git add .
    - name: commit changed files
      run: git commit -m "Auto updating TODO.txt"
    - name: fetch from master
      run: git fetch origin master
    - name: push code to master
      run: git push origin HEAD:master
    - name: Create virtual machine(s)
      run: |
        $vmSku = "${{ github.event.inputs.vmSku }}"
        $vmCount = ${{ github.event.inputs.vmCount }}
        echo "vmSku: $vmSku,  vmCount: $vmCount"

