on:
  push:
  workflow_dispatch:
    inputs:
      vmSku:
        description: 'Virtual Machine SKU'     
        required: true
        default: 'Standard_B2ms'
      vmCount:
        description: 'Virtual Machine Count'     
        required: true
        default: 2

jobs:
  setup:
    name: Setup Azure VM
    runs-on: windows-latest
    steps:
      - name: echo inputs
        run: |
          $vmSku = "${{ github.event.inputs.vmSku }}"
          $vmCount = ${{ github.event.inputs.vmCount }}
          echo "vmSku: $vmSku, vmCount: $vmCount"

