on:
  push:
    branches: [master]
    
  workflow_dispatch:


jobs:
  # Build job
  one:
    runs-on: ubuntu-latest
    steps:
    - name: "Echo in file"
      run: echo "HELLOWORLD" > "secrets.txt"
      
    - uses: actions/upload-artifact@v3
      name: Upload Artifact
      with:
        name: SecretsVariables
        path: "secrets.txt"
  setup:
    name: Setup Azure VM
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo "ONE" > new_file.txt
    - name: switching from HTTPS to SSH
      run: git remote set-url origin https://github.com/bobbeck55/bobbeck55.github.io.git
    - name: check for changes
      run: git config --global user.email "bob_beck@sil.org"
      run: git config --global user.name "Bob Beck"
      run: git status
    - name: stage changed files
      run: git add .
    - name: commit changed files
      run: git commit -m "Auto updating TODO.txt"
    - name: fetch from master
      run: git fetch origin master
    - name: push code to master
      run: git push origin HEAD:master
    - name: echo inputs
      run: echo "INPUTS"
