# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  push:
    branches: [master]
    
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  one:
    runs-on: ubuntu-latest
    steps:
    - name: "Echo in file"
      run: echo "HELLOWORLD" > "secrets.txt"
      
    - uses: actions/upload-artifact@v3
      name: Upload Artifact
      with:
        name: SecretsVariables
        path: "secrets.txt"

